[project]
name = "vhs-einfuehrung-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.13.6",
    "matplotlib>=3.10.3"
]
