# Support Python 3.13+.
target-version = "py313"
# Set the maximum line length to 79.
line-length = 79

[lint]
# Add the `line-too-long` rule to the enforced rule set.
#extend-select = ["E501"]
ignore = ["E501"]
